### ISSUE TITLE
Could do with a code review.

### ISSUE THREAD

**Issue by thejpster** [thejpster/tm4c123x-hal#1]

**Comment by jamesmunns** [comment]
@thejpster hey, I'm bitshiftmask from IRC. Feel free to tag me, hopefully I can check this out tonight or tomorrow

**Comment by thejpster** [comment]
I've been working in master, so feel free to cast your eye over that. Serial, GPIO and busy-wait delays are done - largely based on stm32f30x-hal. The other modules will be broadly similar in style.

**Comment by thejpster** [comment]
Much appreciated, by the way! Also, Zurich was excellent.

**Comment by thejpster** [comment]
This was in PR #2
